version: '3'

services:
  db:
    image: postgres
  core-api:
    env_file:
        - .env
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - "./core-api:/core-api"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
