# Generated by Django 2.2.7 on 2019-11-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing', models.CharField(max_length=25, unique=True)),
                ('meaning', models.CharField(max_length=50)),
                ('level', models.PositiveIntegerField(default=1)),
                ('important_reading', models.CharField(choices=[('kunyomi', "kun'yomi"), ('onyomi', "on'yomi")], default='onyomi', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KanjiReadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(choices=[('kunyomi', "kun'yomi"), ('onyomi', "on'yomi")], default='onyomi', max_length=10)),
                ('reading', models.CharField(max_length=25)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='lesson.Kanji')),
            ],
        ),
    ]
