# Generated by Django 2.2.7 on 2019-11-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing', models.CharField(max_length=25, unique=True)),
                ('kana_type', models.CharField(choices=[('hiragana', 'hiragana'), ('katakana', 'katakana')], max_length=10)),
            ],
        ),
    ]
