# Generated by Django 2.2.7 on 2019-11-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_kana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing', models.CharField(max_length=25, unique=True)),
                ('kana', models.CharField(max_length=25)),
                ('meaning', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='kanji',
            name='meaning',
            field=models.CharField(max_length=100),
        ),
    ]
